### ISSUE TITLE
Unclear how RPK are transferred in COSE

### ISSUE THREAD

**Issue by emanjon** [EricssonResearch/EDHOC#26]
Unclear how RPK are transferred in COSE. Are RPK identified with kid, sent as a COSE_Key, or as sent as COSE_X509. This affects whether the ? in "? Cert_V" is needed.

**Comment by jimsch** [comment]
Well - a RPK cannot be set by a certificate so that option is out.  RPK is generally not used with COSE except for the ephemeral keys used in ephemeral-static key agreement operations, this is because there needs to be a validation step as well someplace.

Where do you think you need to identify the RPK?  

* No RPKs are currently being used for encryption as all key agreement operations are done outside of COSE.
* For signature operations, I would expect that the COSE_Key that is distributed to both parties to have a kid value as part of it so that it can be consistently referred to.

**Comment by gselander** [comment]
RPK may be encoded as in RFC7250, in which case the X.509-based identifications may be used, but in general the use of kid seems more optimal for constrained environments, and the former still requires some out of band identification. Anyway, both cases are covered in the section 4.1 so I close this issue.
