### ISSUE TITLE
Do arrays need to be serialized and if so when?

### ISSUE THREAD

**Issue by emanjon** [EricssonResearch/EDHOC#30]
OSCOAP talks about serialised array but I cannot find this in COSE. Is it needed to say than an array is serialized and if so when?

**Comment by jimsch** [comment]
@emanjon two questions 
1.  Is this in the right issues list - i.e. should it be in OSCOAP
2. Can you expand on what you are asking about?  I don't know enough of the question to be able to respond.

**Comment by fpalombini** [comment]
I checked the latest OSCOAP, and there is no more mentioning of "serialized arrays". I think that's good since I don't think we want to use serialized arrays at all (adding >1B for no reason). While there is a point for serializing maps (order of elements) I don't see any point in using serialized arrays.

I suggest we close this unless anyone has something to add.

**Comment by jimsch** [comment]
@fpalombini - maps are unordered and arrays are ordered - are you backwards?

**Comment by fpalombini** [comment]
no, that's what I meant too, serialization is to keep the order of elements, so it only makes sense for maps, since arrays are ordered.

**Comment by jimsch** [comment]
Canonicalization is to keep the order of the elements, serialization is just to write them out.  That is how I use the terms so you can see why I was confused.
