### ISSUE TITLE
Remove the encrypted blob in 5.2.1

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#33]
Message 1 for symmetric should not have the encrypted block.  Two reasons
1.  This is a difference between the symmetric and asymmetric types which means that a usage analysis by an application would need to require one case or do different things.
2.  If you wanted, for example, to pass a CWT as part of the EXT_1 fields, it would make it impossible.  You need to the contents of the CWT to decrypt the Enc blob, but it is protected by the Enc blob.

If people find they really want this then it can be added as an extension and life can go on.

**Comment by jimsch** [comment]
Note: I find Dan's comment from the F2F to not be very compelling.  This problem is always going be true if you have a PSK.  It is just as true for TLS/DTLS as it is here when PSK is used w/o adding in the DH component.  Given that these are expected to be one time secrets and are binary rather than user inputs I am not overly worried about the dictionary attack.  However, that is just a cost of doing things w/ PSK.

**Comment by gselander** [comment]
We don't have a use case for encrypting EXT_1, it was introduced just because we can. But integrity protecting message 1 is a feature which may prevent the server from doing work, as discussed in #38.

There would still be a difference between symmetric and asymmetric. Please elaborate on the issue with "usage analysis" as in 1. above.
