### ISSUE TITLE
Must Discard is usually a bad idea

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#35]
I really worry about the amount of must discard that comes into many of these protocols.  The problem is that if transmission is really expensive - both sending and receiving then UDP retries are going to be costly.  Need to look at the relative costs of receiving and processing messages vs sending a fail and preventing retries.

**Comment by gselander** [comment]
As you remark here and elsewhere, this depends on the underlying layer. 

In case of CoAP over TCP this is not an issue. If we use EDHOC over CoAP NON, this is not an issue either. In both these cases, discard would be the right thing to do, wouldn't it?

However using CoAP CON for message_3 could be useful as an acknowledgement of message received. (How is that exposed to the application?)

Alternatively we could recommend the use of a generic error message, like we now do for OSCOAP.
Since EDHOC is independent of underlying layer, that would be a general statement, although we may want to specify error codes specifically for CoAP (HTTP).

Anyone has a concrete proposal?

**Comment by jimsch** [comment]
People keep saying that CoAP over TCP is not a problem, I disagree.  I have my doubts that the UDP->TCP proxies are going to get the correct behavior on these things.  What does a client do if it gets an ACK message but never gets any other message?  Will they always get ACK mesages?  Similarly, what happens if you do TCP->UDP?  The client does not expect errors but the server is going to generate them anyway?

Generate a consistent, uninformative error message - probably BAD REQUEST in most cases for any CON message (which means that the TCP people are going to normally be out of it as they never have CON messages).
