### ISSUE TITLE
Introduction to section 5 refers to CWT

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#37]
The introduction refers to being able to carry a CWT as the KID value.  I don't care for this in general, but if you do this make it as the top level and not below.  I assume this would always be a COSE object so it would be an array vs a bstr.  Alt would be to tag them if CWT really gets the tag assigned.

**Comment by gselander** [comment]
One reason for carrying CWT in KID was to be able to protect message_1 with K_1 and transport the key from which K_1 is derived in the CWT, as an ACE Access Token. Given that we remove encryption (even if we keep integrity protection) of message_1, the CWT may as well be transported in EXT_1, in which case I assume this issue is obsolete? If not, please explain what you mean by "top level" in this context.

**Comment by jimsch** [comment]
Yes that would render the issue obsolete.
