### ISSUE TITLE
Change () to [] for CBOR sequences to align with recommendation in draft-cbor-sequence

### ISSUE THREAD

**Issue by emanjon** [EricssonResearch/EDHOC#90]

**Comment by martindisch** [comment]
I've been studying the draft for an experimental implementation of mine and I noticed that a couple of versions ago, the message format was changed from CBOR arrays to sequences.

I haven't been able to find the reasoning behind it, could you point me to where that was discussed?

**Comment by emanjon** [comment]
I don't think there is any online discussion. The simple reason behind the change was to save 1 byte in message 1 and 2 and two bytes in message 3. The change was also influenced by the decision by the CBOR WG to formally standardize CBOR sequences. But they have been supported by some CBOR libraries for a long time.

This issue does not suggest to change it back, but suggest changing the notation. Recommendation in the CBOR working group was to use [] with a comment for now, but draft-ietf-cbor-sequences says that CDDL might standadize () for CBOR sequences in the future, so maybe it is best to just keep that notation.

Note: If the () is kept, Appendix A.1 should take more about CBOR sequences...

**Comment by martindisch** [comment]
Thanks for getting back to me about that. I suspected it had to do with reducing message size, but if that's the case, the following confused me somewhat:
> Format message_1 as the sequence of CBOR data items specified in Section 4.2.1 and encode it to a byte string (see Appendix A.1).

It's the same for the other two messages. Assuming this example message_1:
```
message_1 = (
  1,
  0,
  h'0102',
  h'0304',
)
```
whose byte representation would be
```
01      # unsigned(1)
00      # unsigned(0)
42      # bytes(2)
   0102 # "\x01\x02"
42      # bytes(2)
   0304 # "\x03\x04"
```
which is 8 bytes. If we then encode it to a bstr for transmission as instructed, we add another byte for the major type and length of the bstr.
```
48                  # bytes(8)
   0100420102420304 # "\x01\x00B\x01\x02B\x03\x04"
```
That's now 9 bytes, the same number as if we were directly using an array instead of the sequence encoded to a bstr.
```
84         # array(4)
   01      # unsigned(1)
   00      # unsigned(0)
   42      # bytes(2)
      0102 # "\x01\x02"
   42      # bytes(2)
      0304 # "\x03\x04"
```
Am I missing something? Maybe I didn't think it through and there are cases where the sequence approach does save bytes?

Concerning the notation, for what it's worth, I personally would stick with () because using the array notation [] even with a comment is likely to confuse people.

**Comment by emanjon** [comment]
>Thanks for getting back to me about that. I suspected it had to do with reducing message size, but if that's the case, the >following confused me somewhat:

Agree that that sentence is confusing. Your message should be send as 8 byte over the wire

01      # unsigned(1)

00      # unsigned(0)

42      # bytes(2)

   0102 # "\x01\x02"

42      # bytes(2)

   0304 # "\x03\x04"

i.e. it should not be wrapped in a byte string. The CBOR specification talks about data item is a general sense, i.e. 1 is a CBOR data item and 0x01 is an encoded CBOR data item….

>Concerning the notation, for what it's worth, I personally would stick with () because using the array notation [] even with a >comment is likely to confuse people.
I agree, we should probably keep () unless the CBOR WG standardizes something else..

**Comment by martindisch** [comment]
Alright, that clears it up. Thank you!

**Comment by emanjon** [comment]
Then we go with the () notation for the moment. Closing this as all issues seem to have been addressed.
